/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_color_free(a: number): void;
export function __wbg_get_color_r(a: number): number;
export function __wbg_set_color_r(a: number, b: number): void;
export function __wbg_get_color_g(a: number): number;
export function __wbg_set_color_g(a: number, b: number): void;
export function __wbg_get_color_b(a: number): number;
export function __wbg_set_color_b(a: number, b: number): void;
export function __wbg_get_global_env_light_color(a: number): number;
export function __wbg_set_global_env_light_color(a: number, b: number): void;
export function __wbg_get_global_ambient_light_color(a: number): number;
export function __wbg_set_global_ambient_light_color(a: number, b: number): void;
export function __wbg_get_global_gradient1(a: number): number;
export function __wbg_set_global_gradient1(a: number, b: number): void;
export function __wbg_get_global_gradient2(a: number): number;
export function __wbg_set_global_gradient2(a: number, b: number): void;
export function __wbg_client_free(a: number): void;
export function movement_new(): number;
export function movement_from(a: number, b: number): number;
export function client_new(a: number, b: number): number;
export function client_update(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): void;
export function client_render(a: number): void;
export function __wbg_set_global_fov(a: number, b: number): void;
export function __wbg_set_outmsg_time(a: number, b: number): void;
export function __wbg_set_outmsg_fps(a: number, b: number): void;
export function __wbg_set_movement_x(a: number, b: number): void;
export function __wbg_set_movement_y(a: number, b: number): void;
export function __wbg_get_global_fov(a: number): number;
export function __wbg_get_outmsg_time(a: number): number;
export function __wbg_get_outmsg_fps(a: number): number;
export function __wbg_get_movement_x(a: number): number;
export function __wbg_get_movement_y(a: number): number;
export function __wbg_global_free(a: number): void;
export function __wbg_outmsg_free(a: number): void;
export function __wbg_movement_free(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h76b1c6c92818c84a(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h46130d05b1f8da29(a: number, b: number, c: number, d: number): void;
