/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_client_free(a: number): void;
export function __wbg_movement_free(a: number): void;
export function __wbg_get_movement_x(a: number): number;
export function __wbg_set_movement_x(a: number, b: number): void;
export function __wbg_get_movement_y(a: number): number;
export function __wbg_set_movement_y(a: number, b: number): void;
export function movement_new(): number;
export function movement_from(a: number, b: number): number;
export function client_new(a: number): number;
export function client_update(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): void;
export function client_render(a: number): void;
export function __wbg_color_free(a: number): void;
export function __wbg_outmsg_free(a: number): void;
export function __wbg_get_outmsg_time(a: number): number;
export function __wbg_set_outmsg_time(a: number, b: number): void;
export function __wbg_get_outmsg_fps(a: number): number;
export function __wbg_set_outmsg_fps(a: number, b: number): void;
export function __wbg_get_outmsg_env_light_color_r(a: number): number;
export function __wbg_set_outmsg_env_light_color_r(a: number, b: number): void;
export function __wbg_get_outmsg_env_light_color_g(a: number): number;
export function __wbg_set_outmsg_env_light_color_g(a: number, b: number): void;
export function __wbg_get_outmsg_env_light_color_b(a: number): number;
export function __wbg_set_outmsg_env_light_color_b(a: number, b: number): void;
export function __wbg_get_outmsg_ambient_light_color_r(a: number): number;
export function __wbg_set_outmsg_ambient_light_color_r(a: number, b: number): void;
export function __wbg_get_outmsg_ambient_light_color_g(a: number): number;
export function __wbg_set_outmsg_ambient_light_color_g(a: number, b: number): void;
export function __wbg_get_outmsg_ambient_light_color_b(a: number): number;
export function __wbg_set_outmsg_ambient_light_color_b(a: number, b: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h745a4db96a614b76(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hd9cdf56ac7f94909(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h6af9fd5c96c1b253(a: number, b: number, c: number, d: number): void;
